name: Mandala CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        run: |
          sudo apt update
          sudo apt install -y qtbase5-dev qtchooser qt5-qmake build-essential qttools5-dev-tools

      - name: Generate translations
        run: lrelease *.ts

      - name: Configure
        run: qmake CONFIG+=release

      - name: Build
        run: make -j$(nproc)